networks:
  jamms-network:
    driver: bridge

services:
  # Development Server
  server-dev:
    container_name: jamms_finance_dev
    image: jamms_finance_dev:v1.0
    build:
      context: ./code
      dockerfile: Dockerfile.dev
    ports:
      - "2517:2517"
    volumes:
      - ./code:/code
    environment:
      - ENVIRONMENT=production
      - ALLOWED_ORIGIN_URLS=http://localhost:5173
      - SQLITE_DATABASE_FILE_PATH=finance.db
      - PORT=2517
    networks:
      - jamms-network
    profiles:
      - dev

  server:
    container_name: jamms_finance
    image: jamms_finance:v1.0
    build:
      context: ./code
      dockerfile: Dockerfile
      target: production
    ports:
      - "2517:2517"
    environment:
      - ENVIRONMENT=production
      - SQLITE_DATABASE_FILE_PATH=finance.db
      - PORT=2517
    restart: unless-stopped
    networks:
      - jamms-network
    profiles:
      - prod
