volumes:
  qurtesy-data:


networks:
  qurtesy-network:
    driver: bridge

services:
  db:
    container_name: qurtesy_postgre
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_static:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  code:
    container_name: qurtesy_code
    build: ./code
    ports:
      - "8085:8085"
    depends_on:
      - db
    volumes:
      - ./db_dump:/code/db_dump
      - ./server_cache:/root/.cache
