volumes:
  qurtesy-data:


networks:
  qurtesy-network:
    driver: bridge

services:
  db:
    container_name: qurtesy_postgre
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_static:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  code:
    container_name: qurtesy_code
    build: ./code
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./db_dump:/db_dump
