FROM python:3.12

WORKDIR /code/ms1

COPY ./requirements.txt /code/ms1/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/ms1/requirements.txt

COPY ./ms1 /code/ms1/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]