FROM python:3.12

WORKDIR /code/ms2

COPY ./requirements.txt /code/ms2/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/ms2/requirements.txt

COPY ./ms2 /code/ms2/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]